### ISSUE TITLE
How is theta calculated?

### ISSUE THREAD

**Issue by mathycee** [han-cai/reinforce-bid#1]
Hi,

In each campaign folder there is a test.theta.txt file and the 3rd field in that file is theta. I was wondering how you calculated that? Did you use L1 logistic regression? I couldn't find the code in you Python folder that does that.

Thank you!

**Comment by han-cai** [comment]
We train a logistic regression model to predict user response (i.e., theta). Please refer to "python/urp.py" for further details.

**Comment by anjeshv** [comment]
Hi,

In each campaign, folder there should be rlb_dnb_save_points text file.I was wondering what data this file contains and how to use that file? If you use any algo for that, give a brief description.

Thank you!
