### ISSUE TITLE
/info.txt How did you get this file from make-ipinyou-data folder.

### ISSUE THREAD

**Issue by sunithak** [han-cai/reinforce-bid#3]
What is info.txt encoding? It is not utf.8
Can you please update the code for converting the data from make-ipinyou-data. It is difficult to understand with out info.txt reading. Thank you.

**Comment by rookiedali** [comment]
Have you solved it? I have the same problem. It is unable to view info.txt.

**Comment by han-cai** [comment]
I have changed the encoding of these files. They should be readable now.

**Comment by rookiedali** [comment]
> I have changed the encoding of these files. They should be readable now.

Thank you, sir. Maybe it's because I downloaded it before. I wiil try to re-download it.
